export const permissionList = {
  Organization: {
    add: "add_Organization",
    view: "view_Organization",
    delete: "delete_Organization",
    edit: "edit_Organization",
    export: "export_Organization",
  },
  Event: {
    add: "add_Event",
    view: "view_Event",
    delete: "delete_Event",
    edit: "edit_Event",
    export: "export_Event",
  },
  EventFilter: {
    add: "add_EventFilter",
    view: "view_EventFilter",
    delete: "delete_EventFilter",
    edit: "edit_EventFilter",
    export: "export_EventFilter",
  },
  Customer: {
    add: "add_Customer",
    view: "view_Customer",
    delete: "delete_Customer",
    edit: "edit_Customer",
    export: "export_Customer",
  },
  BookingTemplates: {
    add: "add_BookingTemplates",
    view: "view_BookingTemplates",
    delete: "delete_BookingTemplates",
    edit: "edit_BookingTemplates",
    export: "export_BookingTemplates",
  },
  Bookings: {
    add: "add_Bookings",
    view: "view_Bookings",
    delete: "delete_Bookings",
    edit: "edit_Bookings",
    export: "export_Bookings",
  },
  BookingsAccessRule: {
    add: "add_BookingsAccessRule",
    view: "view_BookingsAccessRule",
    delete: "delete_BookingsAccessRule",
    edit: "edit_BookingsAccessRule",
    export: "export_BookingsAccessRule",
  },
  QuotationTemplates: {
    add: "add_QuotationTemplates",
    view: "view_QuotationTemplates",
    delete: "delete_QuotationTemplates",
    edit: "edit_QuotationTemplates",
    export: "export_QuotationTemplates",
  },
  Quotations: {
    add: "add_Quotations",
    view: "view_Quotations",
    delete: "delete_Quotations",
    edit: "edit_Quotations",
    export: "export_Quotations",
  },
  QuotationsAccessRule: {
    add: "add_QuotationsAccessRule",
    view: "view_QuotationsAccessRule",
    delete: "delete_QuotationsAccessRule",
    edit: "edit_QuotationsAccessRule",
    export: "export_QuotationsAccessRule",
  },
  Form: {
    add: "add_Form",
    view: "view_Form",
    delete: "delete_Form",
    edit: "edit_Form",
    export: "export_Form",
  },
  Inspection: {
    add: "add_Inspection",
    view: "view_Inspection",
    delete: "delete_Inspection",
    edit: "edit_Inspection",
    export: "export_Inspection",
  },
  FormAccessRule: {
    add: "add_FormAccessRule",
    view: "view_FormAccessRule",
    delete: "delete_FormAccessRule",
    edit: "edit_FormAccessRule",
    export: "export_FormAccessRule",
  },
  InspectionReport: {
    add: "add_InspectionReport",
    view: "view_InspectionReport",
    delete: "delete_InspectionReport",
    edit: "edit_InspectionReport",
    export: "export_InspectionReport",
  },
  InspectionSchedules: {
    add: "add_InspectionSchedules",
    view: "view_InspectionSchedules",
    delete: "delete_InspectionSchedules",
    edit: "edit_InspectionSchedules",
    export: "export_InspectionSchedules",
  },
  Activity: {
    add: "add_Activity",
    view: "view_Activity",
    delete: "delete_Activity",
    edit: "edit_Activity",
    export: "export_Activity",
  },
  Invoice: {
    add: "add_Invoice",
    view: "view_Invoice",
    delete: "delete_Invoice",
    edit: "edit_Invoice",
    export: "export_Invoice",
  },
  Tariffs: {
    add: "add_Tariffs",
    view: "view_Tariffs",
    delete: "delete_Tariffs",
    edit: "edit_Tariffs",
    export: "export_Tariffs",
  },
  Region: {
    add: "add_Region",
    view: "view_Region",
    delete: "delete_Region",
    edit: "edit_Region",
    export: "export_Region",
  },
  Country: {
    add: "add_Country",
    view: "view_Country",
    delete: "delete_Country",
    edit: "edit_Country",
    export: "export_Country",
  },
  Territory: {
    add: "add_Territory",
    view: "view_Territory",
    delete: "delete_Territory",
    edit: "edit_Territory",
    export: "export_Territory",
  },
  Location: {
    add: "add_Location",
    view: "view_Location",
    delete: "delete_Location",
    edit: "edit_Location",
    export: "export_Location",
  },
  SystemParameters: {
    add: "add_SystemParameters",
    view: "view_SystemParameters",
    delete: "delete_SystemParameters",
    edit: "edit_SystemParameters",
    export: "export_SystemParameters",
  },
  UserPermission: {
    add: "add_UserPermission",
    view: "view_UserPermission",
    delete: "delete_UserPermission",
    edit: "edit_UserPermission",
    export: "export_UserPermission",
  },
  UserRole: {
    add: "add_UserRole",
    view: "view_UserRole",
    delete: "delete_UserRole",
    edit: "edit_UserRole",
    export: "export_UserRole",
  },
  OrganizationUser: {
    add: "add_OrganizationUser",
    view: "view_OrganizationUser",
    delete: "delete_OrganizationUser",
    edit: "edit_OrganizationUser",
    export: "export_OrganizationUser",
  },
  UserDepartment: {
    add: "add_UserDepartment",
    view: "view_UserDepartment",
    delete: "delete_UserDepartment",
    edit: "edit_UserDepartment",
    export: "export_UserDepartment",
  },
  Logs: {
    add: "add_Logs",
    view: "view_Logs",
    delete: "delete_Logs",
    edit: "edit_Logs",
    export: "export_Logs",
  },
  UserSecurity: {
    add: "add_UserSecurity",
    view: "view_UserSecurity",
    delete: "delete_UserSecurity",
    edit: "edit_UserSecurity",
    export: "export_UserSecurity",
  },
  Alert: {
    add: "add_Alert",
    view: "view_Alert",
    delete: "delete_Alert",
    edit: "edit_Alert",
    export: "export_Alert",
  },
  InspectionName: {
    add: "add_InspectionName",
    view: "view_InspectionName",
    delete: "delete_InspectionName",
    edit: "edit_InspectionName",
    export: "export_InspectionName",
  },
  InspectionStatus: {
    add: "add_InspectionStatus",
    view: "view_InspectionStatus",
    delete: "delete_InspectionStatus",
    edit: "edit_InspectionStatus",
    export: "export_InspectionStatus",
  },
  BookingStatus: {
    add: "add_BookingStatus",
    view: "view_BookingStatus",
    delete: "delete_BookingStatus",
    edit: "edit_BookingStatus",
    export: "export_BookingStatus",
  },
  GeneralStatus: {
    add: "add_GeneralStatus",
    view: "view_GeneralStatus",
    delete: "delete_GeneralStatus",
    edit: "edit_GeneralStatus",
    export: "export_GeneralStatus",
  },
  Service: {
    add: "add_Service",
    view: "view_Service",
    delete: "delete_Service",
    edit: "edit_Service",
    export: "export_Service",
  },
  Contractor: {
    add: "add_Contractor",
    view: "view_Contractor",
    delete: "delete_Contractor",
    edit: "edit_Contractor",
    export: "export_Contractor",
  },
  StatusAtrributes: {
    add: "add_StatusAtrributes",
    view: "view_StatusAtrributes",
    delete: "delete_StatusAtrributes",
    edit: "edit_StatusAtrributes",
    export: "export_StatusAtrributes",
  },
  CustomAttributes: {
    add: "add_CustomAttributes",
    view: "view_CustomAttributes",
    delete: "delete_CustomAttributes",
    edit: "edit_CustomAttributes",
    export: "export_CustomAttributes",
  },
  InternalAttributes: {
    add: "add_InternalAttributes",
    view: "view_InternalAttributes",
    delete: "delete_InternalAttributes",
    edit: "edit_InternalAttributes",
    export: "export_InternalAttributes",
  },
  ExternalAttributes: {
    add: "add_ExternalAttributes",
    view: "view_ExternalAttributes",
    delete: "delete_ExternalAttributes",
    edit: "edit_ExternalAttributes",
    export: "export_ExternalAttributes",
  },
  ActivityStatus: {
    add: "add_ActivityStatus",
    view: "view_ActivityStatus",
    delete: "delete_ActivityStatus",
    edit: "edit_ActivityStatus",
    export: "export_ActivityStatus",
  },
  TariffRateType: {
    add: "add_TariffRateType",
    view: "view_TariffRateType",
    delete: "delete_TariffRateType",
    edit: "edit_TariffRateType",
    export: "export_TariffRateType",
  },
  FindingsCategory: {
    add: "add_FindingRecommendationMainCategory",
    view: "view_FindingRecommendationMainCategory",
    delete: "delete_FindingRecommendationMainCategory",
    edit: "edit_FindingRecommendationMainCategory",
    export: "export_FindingRecommendationMainCategory",
  },

  FindingsSubCategory: {
    add: "add_FindingRecommendationSubCategory",
    view: "view_FindingRecommendationSubCategory",
    delete: "delete_FindingRecommendationSubCategory",
    edit: "edit_FindingRecommendationSubCategory",
    export: "export_FindingRecommendationSubCategory",
  },
};
