const fakeData = {
  headers: {
    booking_id: "Booking ID",
    customer_name: "Customer Name",
    inspection_type: "Inspection Type",
    inspection_date: "Inspection Date",
    location: "Location",
    status: "Status(All)",
  },
  page: 1,
  total: 3,
  pages: 2,
  size: 2,
  items: [
    {
      id: 0,
      booking_id: "BAS00987",
      customer_name: "Ace Marine Services",
      inspection_type: "Mooring Procedures Training",
      inspection_date: "22nd Jan, 2023",
      location: "Brazil",
      status: "Completed",
      archivedCount: 10,
    },
    {
      id: 1,
      booking_id: "BAS00987",
      customer_name: "Ace Marine Services",
      inspection_type: "Mooring Procedures Training",
      inspection_date: "22nd Jan, 2023",
      location: "Brazil",
      status: "Invoiced",
      archivedCount: 10,
    },
    {
      id: 2,
      booking_id: "BAS00987",
      customer_name: "Ace Marine Services",
      inspection_type: "Mooring Procedures Training",
      inspection_date: "22nd Jan, 2023",
      location: "Brazil",
      status: "Completed",
      archivedCount: 10,
    },
    {
      id: 3,
      booking_id: "BAS00987",
      customer_name: "Ace Marine Services",
      inspection_type: "Mooring Procedures Training",
      inspection_date: "22nd Jan, 2023",
      location: "Brazil",
      status: "Completed",
      archivedCount: 10,
    },
    {
      id: 4,
      booking_id: "BAS00987",
      customer_name: "Ace Marine Services",
      inspection_type: "Mooring Procedures Training",
      inspection_date: "22nd Jan, 2023",
      location: "Brazil",
      status: "Completed",
      archivedCount: 10,
    },
    {
      id: 5,
      booking_id: "BAS00987",
      customer_name: "Ace Marine Services",
      inspection_type: "Mooring Procedures Training",
      inspection_date: "22nd Jan, 2023",
      location: "Brazil",
      status: "Completed",
      archivedCount: 10,
    },
    {
      id: 6,
      booking_id: "BAS00987",
      customer_name: "Ace Marine Services",
      inspection_type: "Mooring Procedures Training",
      inspection_date: "22nd Jan, 2023",
      location: "Brazil",
      status: "Completed",
      archivedCount: 10,
    },
    {
      id: 7,
      booking_id: "BAS00987",
      customer_name: "Ace Marine Services",
      inspection_type: "Mooring Procedures Training",
      inspection_date: "22nd Jan, 2023",
      location: "Brazil",
      status: "Completed",
      archivedCount: 10,
    },
  ],
};

export default fakeData;
